### ISSUE TITLE
Workshop outline

### ISSUE THREAD

**Issue by tomwayson** [tomwayson/building-enterprise-gis-apps-with-react#1]
Here's my first pass:

Conceptual intro by Dave, then we get into workshops as follows:

- Building an Application
  - Scaffold the application
    - Prerequisites (node, npm and git should already be installed)
    - Run the command - `npx create-react-app my-app`
    - Run the app - `yarn start`
  - Add a UI library
    - [Install bootstrap and node-sass]((https://create-react-app.dev/docs/adding-bootstrap/))
    - [Install reactstrap](https://reactstrap.github.io/)
    - Add some JSX and styles (home page jumbotron)
  - Add a smoke test
    - modify App test to expect the new DOM
- Architecture
  - Add a router
    - Install React Router
    - Build some [routes](https://reacttraining.com/react-router/web/example/basic)
      - Build route components
        - Home - move jumbotron from above (& add search form?)
        - Items - table based on mock response data?
      - Link together with a [navbar](https://reactstrap.github.io/components/navbar/)
  - Re-use components
    - Refactor navbar into a component (to isolate state)?
    - Write search form as a reusable component
    - Add search component to items page
    - Add a test for the search component
- Use the ArcGIS Platform
  - Get search working 
    - install ArcGIS REST JS (request & portal)
    - wire up to Items route component
  - Auth
    - Register your app with ArcGIS.com
    - Adding Sign-In to Our app
      - install ArcGIS REST JS (auth)
      - add sign in button to navbar & click handler to App component
        - calls `UserSession.beginOAuth2()`
        - stores in cookie
      - Persisting Session
        - read from cookie when app loads
      - add sign out button to navbar & click handler to App component
    - Use authentication when searching
      - pass auth to Items route component as a prop
      - add to request options
- Maps
  - Tom does his thing
- Deployment
  - production builds
  - environment variables
  - deployment: https://create-react-app.dev/docs/deployment
    - where to host? Surge?

That would conclude the workshops, people should have successfully deployed an app.

Then we could touch on these concepts:
- Cross-cutting, common, shared state?
  - NOTE: in the Ember app this is where we introduced services under Architecture, but in react app we don't need anything like that at that point. Ultimately we might want use [context](https://reactjs.org/docs/context.html) for auth, so we could introduce that here???
  - Other frameworks - we could point to last-year's [Ember workshop](https://github.com/mjuniper/ambitious-arcgis-app-2019) for 🍎 to 🍏 comparison
  - React [hooks](https://reactjs.org/docs/hooks-intro.html)?
  - i18n?
   - SSR?
   - PWA?

**Comment by steveoh** [comment]
> Prerequisites (node, npm and git should already be installed)

Run the app - yarn start :trollface:

**Comment by dbouwman** [comment]
Looks good! @tomwayson thoughts on where to inject the "zen-of-<X>" content? i.e. I have ~30 slides on zen-of-oAuth... I have/will-have some content for "zen-of-testing"... anyhow - mainly looking at options to re-use the conceptual content we have kicking around from past workshops/talks...

**Comment by tomwayson** [comment]
Yeah @dbouwman - I cobbled the above together entirely from our previous _workshops_, but didn't include the bullet points from the _slides_. I'll take another pass that helps clarify that.

**Comment by tomwayson** [comment]
closing this as it's half implemented in master: https://github.com/tomwayson/building-enterprise-gis-apps-with-react#outline
